version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/traini8
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3309
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: traini8
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123
networks:
  springapimysql-net: